stanford_actions.settings:
  type: config_object
  mapping:
    actions:
      type: sequence
      label: 'VBO Action settings'
      sequence:
        type: stanford_actions.[%key]

stanford_actions.node_clone_action:
  type: mapping
  mapping:
    clone_entities:
      type: sequence
      label: 'Clonable Entity Types'
      sequence:
        type: string
        label: 'Entity Type ID'
